/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module bkadder(CLK, RST_N, A, B, CIN, COUT, S);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  input [15:0] A;
  wire [15:0] A;
  wire \A_reg[0] ;
  wire \A_reg[10] ;
  wire \A_reg[11] ;
  wire \A_reg[12] ;
  wire \A_reg[13] ;
  wire \A_reg[14] ;
  wire \A_reg[15] ;
  wire \A_reg[1] ;
  wire \A_reg[2] ;
  wire \A_reg[3] ;
  wire \A_reg[4] ;
  wire \A_reg[5] ;
  wire \A_reg[6] ;
  wire \A_reg[7] ;
  wire \A_reg[8] ;
  wire \A_reg[9] ;
  input [15:0] B;
  wire [15:0] B;
  wire \B_reg[0] ;
  wire \B_reg[10] ;
  wire \B_reg[11] ;
  wire \B_reg[12] ;
  wire \B_reg[13] ;
  wire \B_reg[14] ;
  wire \B_reg[15] ;
  wire \B_reg[1] ;
  wire \B_reg[2] ;
  wire \B_reg[3] ;
  wire \B_reg[4] ;
  wire \B_reg[5] ;
  wire \B_reg[6] ;
  wire \B_reg[7] ;
  wire \B_reg[8] ;
  wire \B_reg[9] ;
  input CIN;
  wire CIN;
  wire CIN_reg;
  input CLK;
  wire CLK;
  output COUT;
  wire COUT;
  wire \C[16] ;
  input RST_N;
  wire RST_N;
  output [15:0] S;
  wire [15:0] S;
  wire \S_int[0] ;
  wire \S_int[10] ;
  wire \S_int[11] ;
  wire \S_int[12] ;
  wire \S_int[13] ;
  wire \S_int[14] ;
  wire \S_int[15] ;
  wire \S_int[1] ;
  wire \S_int[2] ;
  wire \S_int[3] ;
  wire \S_int[4] ;
  wire \S_int[5] ;
  wire \S_int[6] ;
  wire \S_int[7] ;
  wire \S_int[8] ;
  wire \S_int[9] ;
  sky130_fd_sc_hd__or2_2 _081_ (
    .A(\B_reg[15] ),
    .B(\A_reg[15] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__nor2_2 _082_ (
    .A(\B_reg[14] ),
    .B(\A_reg[14] ),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor2_2 _083_ (
    .A(\B_reg[4] ),
    .B(\A_reg[4] ),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o22a_2 _084_ (
    .A1(\B_reg[7] ),
    .A2(\A_reg[7] ),
    .B1(\B_reg[6] ),
    .B2(\A_reg[6] ),
    .X(_037_)
  );
  sky130_fd_sc_hd__or2_2 _085_ (
    .A(\B_reg[5] ),
    .B(\A_reg[5] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2_2 _086_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_2 _087_ (
    .A(\B_reg[3] ),
    .B(\A_reg[3] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_2 _088_ (
    .A(\B_reg[2] ),
    .B(\A_reg[2] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__or2_2 _089_ (
    .A(_040_),
    .B(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__or2_2 _090_ (
    .A(\B_reg[1] ),
    .B(\A_reg[1] ),
    .X(_043_)
  );
  sky130_fd_sc_hd__a22o_2 _091_ (
    .A1(\B_reg[1] ),
    .A2(\A_reg[1] ),
    .B1(\B_reg[0] ),
    .B2(\A_reg[0] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__o221a_2 _092_ (
    .A1(\B_reg[1] ),
    .A2(\A_reg[1] ),
    .B1(\B_reg[0] ),
    .B2(\A_reg[0] ),
    .C1(CIN_reg),
    .X(_045_)
  );
  sky130_fd_sc_hd__a21oi_2 _093_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_2 _094_ (
    .A(\B_reg[2] ),
    .B(\A_reg[2] ),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_2 _095_ (
    .A(\B_reg[3] ),
    .B(\A_reg[3] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o221a_2 _096_ (
    .A1(_042_),
    .A2(_046_),
    .B1(_047_),
    .B2(_040_),
    .C1(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__o211a_2 _097_ (
    .A1(\B_reg[7] ),
    .A2(\A_reg[7] ),
    .B1(\B_reg[6] ),
    .C1(\A_reg[6] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__a22o_2 _098_ (
    .A1(\B_reg[5] ),
    .A2(\A_reg[5] ),
    .B1(\B_reg[4] ),
    .B2(\A_reg[4] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__a32o_2 _099_ (
    .A1(_037_),
    .A2(_038_),
    .A3(_051_),
    .B1(\A_reg[7] ),
    .B2(\B_reg[7] ),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_2 _100_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o31ai_2 _101_ (
    .A1(_036_),
    .A2(_039_),
    .A3(_049_),
    .B1(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or2_2 _102_ (
    .A(\B_reg[8] ),
    .B(\A_reg[8] ),
    .X(_055_)
  );
  sky130_fd_sc_hd__or2_2 _103_ (
    .A(\B_reg[10] ),
    .B(\A_reg[10] ),
    .X(_056_)
  );
  sky130_fd_sc_hd__or2_2 _104_ (
    .A(\B_reg[11] ),
    .B(\A_reg[11] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__or2_2 _105_ (
    .A(\B_reg[9] ),
    .B(\A_reg[9] ),
    .X(_058_)
  );
  sky130_fd_sc_hd__and3_2 _106_ (
    .A(_056_),
    .B(_057_),
    .C(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand2_2 _107_ (
    .A(\B_reg[9] ),
    .B(\A_reg[9] ),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_2 _108_ (
    .A(\B_reg[8] ),
    .B(\A_reg[8] ),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_2 _109_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_2 _110_ (
    .A(\B_reg[10] ),
    .B(\A_reg[10] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21bo_2 _111_ (
    .A1(_058_),
    .A2(_062_),
    .B1_N(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__and2_2 _112_ (
    .A(\B_reg[11] ),
    .B(\A_reg[11] ),
    .X(_065_)
  );
  sky130_fd_sc_hd__a31o_2 _113_ (
    .A1(_056_),
    .A2(_057_),
    .A3(_064_),
    .B1(_065_),
    .X(_066_)
  );
  sky130_fd_sc_hd__a31o_2 _114_ (
    .A1(_054_),
    .A2(_055_),
    .A3(_059_),
    .B1(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__or2_2 _115_ (
    .A(\B_reg[12] ),
    .B(\A_reg[12] ),
    .X(_068_)
  );
  sky130_fd_sc_hd__o21a_2 _116_ (
    .A1(\B_reg[13] ),
    .A2(\A_reg[13] ),
    .B1(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__o211a_2 _117_ (
    .A1(\B_reg[13] ),
    .A2(\A_reg[13] ),
    .B1(\B_reg[12] ),
    .C1(\A_reg[12] ),
    .X(_070_)
  );
  sky130_fd_sc_hd__a21o_2 _118_ (
    .A1(\B_reg[13] ),
    .A2(\A_reg[13] ),
    .B1(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__a21oi_2 _119_ (
    .A1(_067_),
    .A2(_069_),
    .B1(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_2 _120_ (
    .A(\B_reg[14] ),
    .B(\A_reg[14] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o21ai_2 _121_ (
    .A1(_035_),
    .A2(_072_),
    .B1(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_2 _122_ (
    .A(\B_reg[15] ),
    .B(\A_reg[15] ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21bo_2 _123_ (
    .A1(_034_),
    .A2(_074_),
    .B1_N(_075_),
    .X(\C[16] )
  );
  sky130_fd_sc_hd__o21ai_2 _124_ (
    .A1(\B_reg[0] ),
    .A2(\A_reg[0] ),
    .B1(CIN_reg),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_2 _125_ (
    .A(\B_reg[0] ),
    .B(\A_reg[0] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__or3_2 _126_ (
    .A(\B_reg[0] ),
    .B(\A_reg[0] ),
    .C(CIN_reg),
    .X(_078_)
  );
  sky130_fd_sc_hd__and3_2 _127_ (
    .A(\B_reg[0] ),
    .B(\A_reg[0] ),
    .C(CIN_reg),
    .X(_079_)
  );
  sky130_fd_sc_hd__a31o_2 _128_ (
    .A1(_076_),
    .A2(_077_),
    .A3(_078_),
    .B1(_079_),
    .X(\S_int[0] )
  );
  sky130_fd_sc_hd__nand2_2 _129_ (
    .A(_076_),
    .B(_077_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_2 _130_ (
    .A(\B_reg[1] ),
    .B(\A_reg[1] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and2_2 _131_ (
    .A(_043_),
    .B(_000_),
    .X(_001_)
  );
  sky130_fd_sc_hd__xor2_2 _132_ (
    .A(_080_),
    .B(_001_),
    .X(\S_int[1] )
  );
  sky130_fd_sc_hd__and2b_2 _133_ (
    .A_N(_041_),
    .B(_047_),
    .X(_002_)
  );
  sky130_fd_sc_hd__xnor2_2 _134_ (
    .A(_046_),
    .B(_002_),
    .Y(\S_int[2] )
  );
  sky130_fd_sc_hd__and2b_2 _135_ (
    .A_N(_040_),
    .B(_048_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_2 _136_ (
    .A(_043_),
    .B(_044_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__or2b_2 _137_ (
    .A(_041_),
    .B_N(_045_),
    .X(_005_)
  );
  sky130_fd_sc_hd__o211a_2 _138_ (
    .A1(_036_),
    .A2(_004_),
    .B1(_047_),
    .C1(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor2_2 _139_ (
    .A(_003_),
    .B(_006_),
    .Y(\S_int[3] )
  );
  sky130_fd_sc_hd__and2_2 _140_ (
    .A(\B_reg[4] ),
    .B(\A_reg[4] ),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor2_2 _141_ (
    .A(_036_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_2 _142_ (
    .A(_049_),
    .B(_008_),
    .Y(\S_int[4] )
  );
  sky130_fd_sc_hd__nand2_2 _143_ (
    .A(\B_reg[5] ),
    .B(\A_reg[5] ),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_2 _144_ (
    .A(_038_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_2 _145_ (
    .A(_036_),
    .B(_049_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__or2_2 _146_ (
    .A(_007_),
    .B(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xnor2_2 _147_ (
    .A(_010_),
    .B(_012_),
    .Y(\S_int[5] )
  );
  sky130_fd_sc_hd__nor2_2 _148_ (
    .A(\B_reg[6] ),
    .B(\A_reg[6] ),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_2 _149_ (
    .A(\B_reg[6] ),
    .B(\A_reg[6] ),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and2b_2 _150_ (
    .A_N(_013_),
    .B(_014_),
    .X(_015_)
  );
  sky130_fd_sc_hd__o21ai_2 _151_ (
    .A1(_051_),
    .A2(_011_),
    .B1(_038_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_2 _152_ (
    .A(_015_),
    .B(_016_),
    .Y(\S_int[6] )
  );
  sky130_fd_sc_hd__xnor2_2 _153_ (
    .A(\B_reg[7] ),
    .B(\A_reg[7] ),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o21ai_2 _154_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_014_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_2 _155_ (
    .A(_017_),
    .B(_018_),
    .Y(\S_int[7] )
  );
  sky130_fd_sc_hd__nand2_2 _156_ (
    .A(_055_),
    .B(_061_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xnor2_2 _157_ (
    .A(_054_),
    .B(_019_),
    .Y(\S_int[8] )
  );
  sky130_fd_sc_hd__nand2_2 _158_ (
    .A(_058_),
    .B(_060_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21bo_2 _159_ (
    .A1(_054_),
    .A2(_055_),
    .B1_N(_061_),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_2 _160_ (
    .A(_020_),
    .B(_021_),
    .Y(\S_int[9] )
  );
  sky130_fd_sc_hd__nand2_2 _161_ (
    .A(_056_),
    .B(_063_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a21o_2 _162_ (
    .A1(_054_),
    .A2(_055_),
    .B1(_062_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _163_ (
    .A(_058_),
    .B(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__xnor2_2 _164_ (
    .A(_022_),
    .B(_024_),
    .Y(\S_int[10] )
  );
  sky130_fd_sc_hd__nand2_2 _165_ (
    .A(\B_reg[11] ),
    .B(\A_reg[11] ),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_2 _166_ (
    .A(_057_),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21bo_2 _167_ (
    .A1(_056_),
    .A2(_024_),
    .B1_N(_063_),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_2 _168_ (
    .A(_026_),
    .B(_027_),
    .Y(\S_int[11] )
  );
  sky130_fd_sc_hd__nand2_2 _169_ (
    .A(\B_reg[12] ),
    .B(\A_reg[12] ),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_2 _170_ (
    .A(_068_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_2 _171_ (
    .A(_067_),
    .B(_029_),
    .Y(\S_int[12] )
  );
  sky130_fd_sc_hd__xnor2_2 _172_ (
    .A(\B_reg[13] ),
    .B(\A_reg[13] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21bo_2 _173_ (
    .A1(_067_),
    .A2(_068_),
    .B1_N(_028_),
    .X(_031_)
  );
  sky130_fd_sc_hd__xnor2_2 _174_ (
    .A(_030_),
    .B(_031_),
    .Y(\S_int[13] )
  );
  sky130_fd_sc_hd__and2b_2 _175_ (
    .A_N(_035_),
    .B(_073_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xnor2_2 _176_ (
    .A(_072_),
    .B(_032_),
    .Y(\S_int[14] )
  );
  sky130_fd_sc_hd__nand2_2 _177_ (
    .A(_034_),
    .B(_075_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_2 _178_ (
    .A(_074_),
    .B(_033_),
    .Y(\S_int[15] )
  );
  sky130_fd_sc_hd__dfrtp_2 _179_ (
    .CLK(CLK),
    .D(\S_int[0] ),
    .Q(S[0]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _180_ (
    .CLK(CLK),
    .D(\S_int[1] ),
    .Q(S[1]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _181_ (
    .CLK(CLK),
    .D(\S_int[2] ),
    .Q(S[2]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _182_ (
    .CLK(CLK),
    .D(\S_int[3] ),
    .Q(S[3]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _183_ (
    .CLK(CLK),
    .D(\S_int[4] ),
    .Q(S[4]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _184_ (
    .CLK(CLK),
    .D(\S_int[5] ),
    .Q(S[5]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _185_ (
    .CLK(CLK),
    .D(\S_int[6] ),
    .Q(S[6]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _186_ (
    .CLK(CLK),
    .D(\S_int[7] ),
    .Q(S[7]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _187_ (
    .CLK(CLK),
    .D(\S_int[8] ),
    .Q(S[8]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _188_ (
    .CLK(CLK),
    .D(\S_int[9] ),
    .Q(S[9]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _189_ (
    .CLK(CLK),
    .D(\S_int[10] ),
    .Q(S[10]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _190_ (
    .CLK(CLK),
    .D(\S_int[11] ),
    .Q(S[11]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _191_ (
    .CLK(CLK),
    .D(\S_int[12] ),
    .Q(S[12]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _192_ (
    .CLK(CLK),
    .D(\S_int[13] ),
    .Q(S[13]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _193_ (
    .CLK(CLK),
    .D(\S_int[14] ),
    .Q(S[14]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _194_ (
    .CLK(CLK),
    .D(\S_int[15] ),
    .Q(S[15]),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _195_ (
    .CLK(CLK),
    .D(\C[16] ),
    .Q(COUT),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _196_ (
    .CLK(CLK),
    .D(B[0]),
    .Q(\B_reg[0] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _197_ (
    .CLK(CLK),
    .D(B[1]),
    .Q(\B_reg[1] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _198_ (
    .CLK(CLK),
    .D(B[2]),
    .Q(\B_reg[2] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _199_ (
    .CLK(CLK),
    .D(B[3]),
    .Q(\B_reg[3] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _200_ (
    .CLK(CLK),
    .D(B[4]),
    .Q(\B_reg[4] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _201_ (
    .CLK(CLK),
    .D(B[5]),
    .Q(\B_reg[5] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _202_ (
    .CLK(CLK),
    .D(B[6]),
    .Q(\B_reg[6] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _203_ (
    .CLK(CLK),
    .D(B[7]),
    .Q(\B_reg[7] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _204_ (
    .CLK(CLK),
    .D(B[8]),
    .Q(\B_reg[8] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _205_ (
    .CLK(CLK),
    .D(B[9]),
    .Q(\B_reg[9] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _206_ (
    .CLK(CLK),
    .D(B[10]),
    .Q(\B_reg[10] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _207_ (
    .CLK(CLK),
    .D(B[11]),
    .Q(\B_reg[11] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _208_ (
    .CLK(CLK),
    .D(B[12]),
    .Q(\B_reg[12] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _209_ (
    .CLK(CLK),
    .D(B[13]),
    .Q(\B_reg[13] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _210_ (
    .CLK(CLK),
    .D(B[14]),
    .Q(\B_reg[14] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _211_ (
    .CLK(CLK),
    .D(B[15]),
    .Q(\B_reg[15] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _212_ (
    .CLK(CLK),
    .D(A[0]),
    .Q(\A_reg[0] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _213_ (
    .CLK(CLK),
    .D(A[1]),
    .Q(\A_reg[1] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _214_ (
    .CLK(CLK),
    .D(A[2]),
    .Q(\A_reg[2] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _215_ (
    .CLK(CLK),
    .D(A[3]),
    .Q(\A_reg[3] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _216_ (
    .CLK(CLK),
    .D(A[4]),
    .Q(\A_reg[4] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _217_ (
    .CLK(CLK),
    .D(A[5]),
    .Q(\A_reg[5] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _218_ (
    .CLK(CLK),
    .D(A[6]),
    .Q(\A_reg[6] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _219_ (
    .CLK(CLK),
    .D(A[7]),
    .Q(\A_reg[7] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _220_ (
    .CLK(CLK),
    .D(A[8]),
    .Q(\A_reg[8] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _221_ (
    .CLK(CLK),
    .D(A[9]),
    .Q(\A_reg[9] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _222_ (
    .CLK(CLK),
    .D(A[10]),
    .Q(\A_reg[10] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _223_ (
    .CLK(CLK),
    .D(A[11]),
    .Q(\A_reg[11] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _224_ (
    .CLK(CLK),
    .D(A[12]),
    .Q(\A_reg[12] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _225_ (
    .CLK(CLK),
    .D(A[13]),
    .Q(\A_reg[13] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _226_ (
    .CLK(CLK),
    .D(A[14]),
    .Q(\A_reg[14] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _227_ (
    .CLK(CLK),
    .D(A[15]),
    .Q(\A_reg[15] ),
    .RESET_B(RST_N)
  );
  sky130_fd_sc_hd__dfrtp_2 _228_ (
    .CLK(CLK),
    .D(CIN),
    .Q(CIN_reg),
    .RESET_B(RST_N)
  );
endmodule
